### ISSUE TITLE
[SOLVED] DHCPCD Crash: Possibly net/dhcpcd port used for build is out-of-date compared to one in trueos-ports

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-build#8]
On startup dhcp client using the dhcpcd binary which comes out of box crashes with segmentation fault due to nullptr dereference (ifp->options is null). This occurs at the IPv6 interface initialization stage. The version seems to be **v6.11.5** (FreeBSD ports). The crash does not happen with dhcpcd **v7.0.4** available in latest trueos-ports. As several smoke tests showed DHCP client successfully started.

So one possible solution  is to build Trident with latest trueos-ports.

I noticed that trident-manifest.json has the following. Please confirm whether the directory contains latest from https://github.com/trueos/trueos-ports
>   "ports" : {
>     "type" : "local",
>     "url" : "/usr/ports_tmp",

Please see GDB for details on the issue if [necessary.  
[gdb_dhcpcd_crash_segfault.txt](https://github.com/project-trident/trident-build/files/2485835/gdb_dhcpcd_crash_segfault.txt)

**Comment by RodMyers** [comment]
is this fixed with the latest release

**Comment by maxsteciuk** [comment]
No, unfortunately i still see dhcpcd segfaulting on startup

My guess is  the following is culprit:

> 
>ifconfig_igb0="SYNCDHCP"
> TODO: this line below 
> ifconfig_igb0_ipv6="inet6 accept_rtadv"

**Comment by RodMyers** [comment]
please try with new release

**Comment by maxsteciuk** [comment]
Hi 
I just tried to restart network and fully reboot the system with the previously mentioned configs and dhcpcd didn't coredump

Thank you!
> ifconfig_igb0_ipv6="inet6 accept_rtadv"
> ifconfig_em0_ipv6="inet6 accept_rtadv"
